### ISSUE TITLE
Comment displays poorly when you try to type on mobile

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/mobi-interest#1]
After testing on my phone, I noticed a bug when you actually try to type. Here are the screenshots:

Pre Comment
![img_6706](https://cloud.githubusercontent.com/assets/12280257/10053260/ec487938-61df-11e5-88b0-0f3579883e36.PNG)

Comment box when click in to type
![img_6707](https://cloud.githubusercontent.com/assets/12280257/10053262/ef5ab0fa-61df-11e5-9f05-3052ed2cdf1d.PNG)

Scroll to see type
![img_6708](https://cloud.githubusercontent.com/assets/12280257/10053267/f5429b5e-61df-11e5-9cc9-13e894f4c15a.PNG)

The background appears to take over when you scroll down, but otherwise, not sure what's going on. Note: This bug was in the Chrome app on iPhone 6, but it works well on Safari on iPhone 6.

Let me know if you have any questions. Thanks!

**Comment by schrizsz** [comment]
Is this ok to be closed :dancer:
